server:
  port: 8082

spring:
  application:
    name: upload-service

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    ip-address: 127.0.0.1 #设置当前的实例的IP地址
    prefer-ip-address: true #设置使用IP地址HostName
