server:
  port: 10086

spring:
  application:
    name: ly-registry

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

    #以下数据方便测试使用，上线请关闭
  server:
    enable-self-preservation: false       #关闭自我保护
    eviction-interval-timer-in-ms: 5000   #每隔五秒清空一次服务
