server:
  port: 8081

spring:
  application:
    name: item-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.41.17.189:3306/leyou
    username: root
    password: 123456
  rabbitmq:
    host: 192.168.116.128
    username: wsyslf1996
    password: 61196202e
    virtual-host: /leyou
    template:
      exchange: leyou.item.exchange
    publisher-confirms: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 192.168.116.1
    instance-id: ${spring.application.name}:${server.port}

#mybatis打印sql
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
