server:
  port: 8085
spring:
  application:
    name: sms-service
  redis:
    host: 192.168.116.128 #设置Redis服务器的IP

  # RabbitMQ配置
  rabbitmq:
    host: 192.168.116.128
    username: wsyslf1996
    password: 61196202e
    virtual-host: /leyou
    publisher-confirms: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 192.168.116.1
    instance-id: ${spring.application.name}.${server.port}
    lease-renewal-interval-in-seconds: 5  # 心跳检测频率 测试专用
    lease-expiration-duration-in-seconds: 15 # 失效扫描 测试专用


