server:
  port: 8085

spring:
  application:
    name: sms-service

  #设置Redis服务器的IP
  redis:
    host: 192.168.116.128

  # RabbitMQ配置
  rabbitmq:
    host: 192.168.116.128
    username: wsyslf1996
    password: 61196202e
    virtual-host: /leyou
    publisher-confirms: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 192.168.116.1
    instance-id: ${spring.application.name}.${server.port}
    lease-renewal-interval-in-seconds: 5  # 心跳检测频率 测试专用
    lease-expiration-duration-in-seconds: 15 # 失效扫描 测试专用

ly:
  sms:
    accessKeyId: LTAI4G1XHBpBQ1cN7TxrUcUF           # 自己的accessKeyId
    accessKeySecret: ySZlL8rwvMAK87Mymzm2hlYQJLxSbH # 自己的AccessKeySecret
    signName: 乐优毕设                               # 签名名称
    verifyCodeTemplate: SMS_187939790               # 验证码模板名称



